Gas overlap
beliaev-maksim/ansys-hackathon-mustards pull request #20
Opened 2022-03-03 12:56 UTC by StefanThoene

closes #16 and #15

2022-03-03 13:01 UTC, beliaev-maksim requested changes

2022-03-03 13:01 UTC, beliaev-maksim commented on mustards_game/gas_cloud.py
> +                        self.positions[x, y + 1].gas_level += self.positions[x, y].gas_level / 12
let's set 12 as a variable

2022-03-03 13:01 UTC, beliaev-maksim commented on mustards_game/gas_cloud.py
> +        for x in range(0, int(SCREEN_WIDTH / GAS_SIZE)):
```suggestion
        for x in range(int(SCREEN_WIDTH / GAS_SIZE)):
```

2022-03-04 07:45 UTC, beliaev-maksim commented
@StefanThoene 
need to resolve conflicts

2022-03-04 07:54 UTC, StefanThoene commented
@beliaev-maksim  done

2022-03-04 07:54 UTC, beliaev-maksim approved these changes

2022-03-04 07:55 UTC, merged